### ISSUE TITLE
howto does not correctly reflect how to use your build scripts

### ISSUE THREAD

**Issue by rworkman** [KaMiila/SlackBuilds#2]
As an example, the howto document in the external link mentions downloading of source, yet you state that this is not necessary. Which is it? Perhaps you should write your own howto instead of linking to one at a project which you perceive to be inferior.

**Comment by KaMiila** [comment]
This is nothing but trolling. I am closing this post.

**Comment by rworkman** [comment]
The fact remains that the "howto" linked from your README and the remainder of the text in the README itself are inconsistent. You are certainly free to pretend that reporting a bug is trolling, but it remains a bug, regardless of the state of said bug report. 
As one of the founders and maintainers of the SlackBuilds.org project, I have no objection at all to the idea that you perceive your modified scripts to be better than what we provide - I certainly understand your point of view, and there is some validity to it. However, automatically downloading the source is inconsistent with what we (the royal "we" of the project) are trying to accomplish and thus we choose not to do so at this time (although it's certainly subject to change in the future, even if I personally do not like the idea). I also have no objection to your linking our "howto" document, but I think you should note that parts of it are superseded/invalidated by your own repo's characteristics; otherwise, you run the risk of confusing users by essentially telling them something that is later contradicted.
Your move.
